### ISSUE TITLE
Lineage column does not exist

### ISSUE THREAD

**Issue by Allann** [seven1986/IdentityServer4.MicroService#54]
https://github.com/seven1986/IdentityServer4.MicroService/blob/c53fbfde5efc09801b887b901623f9550c52a807/IdentityServer4.MicroService/Services/AccountService.cs#L63

In the AppUser the Lineage column is set to NotMapped therefore the migrations have excluded it and this staement will fail.

**Comment by seven1986** [comment]
@Allann hi, thanks!
I just updated the code, you see here
![image](https://user-images.githubusercontent.com/20808494/43316115-bc4bf976-91ca-11e8-9d0b-fcfda50d54f1.png)

or if you have already created the database, you can add "Lineage" column to "AspNetUsers" table
![image](https://user-images.githubusercontent.com/20808494/43316188-02df8c9a-91cb-11e8-9226-13d441fffeac.png)
