### ISSUE TITLE
IdentityServer4.MicroService UI 部署

### ISSUE THREAD

**Issue by MetSystem** [seven1986/IdentityServer4.MicroService#64]
![image](https://user-images.githubusercontent.com/7943054/52923659-cd42d980-3363-11e9-9c98-7bf7520c45bf.png)
部署成功,但无法正常使用

**Comment by seven1986** [comment]
具体是哪里出现问题？  无法安装脚手架还是？

**Comment by MetSystem** [comment]
点击开放平台没响应。

**Comment by MetSystem** [comment]
安装我不知道操作是否正确，我直接在应用管理里面操作安装（但没响应）。

**Comment by seven1986** [comment]
@MetSystem  加我微信 wz15026776046

**Comment by MetSystem** [comment]
不好意思，才看到
